_RENAMER_SUPPORTED_EXTRACT_FIELD: set = {
    "DATE", "ALBUM", "CATALOGNUMBER", "ALBUMARTIST", "SOURCE", "QUALITY", "FOLDER_CONTENT", "SCORE"
}

_FIELD_EXTRACT_FROM_TAGS: list = [
    "DATE", "ALBUM", "CATALOGNUMBER", "ALBUMARTIST"
]