from mutagen.id3._specs import PictureType as PT


ID3v23_TO_VORBIS = {
    'TALB': 'ALBUM',
    'TSOA': 'ALBUMSORT',
    'TPE2': 'ALBUMARTIST',
    'TSO2': 'ALBUMARTISTSORT',
    'TPE1': 'ARTIST',
    'TSOP': 'ARTISTSORT',
    'TBPM': 'BPM',
    'COMM': 'COMMENT',
    'TCMP': 'COMPILATION',
    'TCOM': 'COMPOSER',
    'TSOC': 'COMPOSERSORT',
    'TPE3': 'CONDUCTOR',
    'TIT1': 'CONTENTGROUP',
    'TCOP': 'COPYRIGHT',
    'TDAT': 'DATE',
    'TPOS': 'DISCNUMBER',
    'TENC': 'ENCODEDBY',
    'TSSE': 'ENCODERSETTINGS',
    'TOWN': 'FILEOWNER',
    'TFLT': 'FILETYPE',
    'TCON': 'GENRE',
    'GRP1': 'GROUPING',
    'IPLS': 'INITIALKEY',
    'TIPL': 'INVOLVEDPEOPLE',
    'TSRC': 'ISRC',
    'TLAN': 'LANGUAGE',
    'TLEN': 'LENGTH',
    'TEXT': 'LYRICIST',
    'TMED': 'MEDIATYPE',
    'TPE4': 'MIXARTIST',
    'MVNM': 'MOVEMENTNAME',
    'UFID:http://musicbrainz.org': 'MUSICBRAINZ_TRACKID',
    'TRSO': 'NETRADIOOWNER',
    'TRSN': 'NETRADIOSTATION',
    'TOAL': 'ORIGALBUM',
    'TOPE': 'ORIGARTIST',
    'TOFN': 'ORIGFILENAME',
    'TOLY': 'ORIGLYRICIST',
    'TDOR': 'ORIGYEAR',
    'PCST': 'PODCAST',
    'TCAT': 'PODCASTCATEGORY',
    'TDES': 'PODCASTDESC',
    'TGID': 'PODCASTID',
    'TKWD': 'PODCASTKEYWORDS',
    'WFED': 'PODCASTURL',
    'TPUB': 'PUBLISHER',
    'POPM:no@email': 'RATING MM',
    'POPM:Windows Media Player 9 Series': 'RATING WMP',
    'TDRL': 'RELEASETIME',
    'TIT3': 'SUBTITLE',
    'SYLT': 'SYNCEDLYRICS',
    'TIT2': 'TITLE',
    'TSOT': 'TITLESORT',
    'TRCK': 'TRACKNUMBER',
    'USLT': 'UNSYNCEDLYRICS',
    'UFID': 'UNIQUEFILEID',
    'WXXX': 'WWW',
    'WOAR': 'WWWARTIST',
    'WOAF': 'WWWAUDIOFILE',
    'WOAS': 'WWWAUDIOSOURCE',
    'WCOM': 'WWWCOMMERCIALINFO',
    'WCOP': 'WWWCOPYRIGHT',
    'WPAY': 'WWWPAYMENT',
    'WPUB': 'WWWPUBLISHER',
    'WORS': 'WWWRADIOPAGE',
    'TYER': 'YEAR'
}

ID3v24_TO_VORBIS = {
    'TALB': 'ALBUM',
    'TSOA': 'ALBUMSORT',
    'TPE2': 'ALBUMARTIST',
    'TSO2': 'ALBUMARTISTSORT',
    'TPE1': 'ARTIST',
    'TSOP': 'ARTISTSORT',
    'TBPM': 'BPM',
    'COMM': 'COMMENT',
    'TCMP': 'COMPILATION',
    'TCOM': 'COMPOSER',
    'TSOC': 'COMPOSERSORT',
    'TPE3': 'CONDUCTOR',
    'TIT1': 'CONTENTGROUP',
    'TCOP': 'COPYRIGHT',
    'TPOS': 'DISCNUMBER',
    'TENC': 'ENCODEDBY',
    'TSSE': 'ENCODERSETTINGS',
    'TDEN': 'ENCODINGTIME',
    'TOWN': 'FILEOWNER',
    'TFLT': 'FILETYPE',
    'TCON': 'GENRE',
    'GRP1': 'GROUPING',
    'TKEY': 'INITIALKEY',
    'TIPL': 'INVOLVEDPEOPLE',
    'TSRC': 'ISRC',
    'TLAN': 'LANGUAGE',
    'TLEN': 'LENGTH',
    'TEXT': 'LYRICIST',
    'TMED': 'MEDIATYPE',
    'TPE4': 'MIXARTIST',
    'TMOO': 'MOOD',
    'MVNM': 'MOVEMENTNAME',
    'UFID:http://musicbrainz.org': 'MUSICBRAINZ_TRACKID',
    'TMCL': 'MUSICIANCREDITS',
    'TRSO': 'NETRADIOOWNER',
    'TRSN': 'NETRADIOSTATION',
    'TOAL': 'ORIGALBUM',
    'TOPE': 'ORIGARTIST',
    'TOFN': 'ORIGFILENAME',
    'TOLY': 'ORIGLYRICIST',
    'TDOR': 'ORIGYEAR',
    'PCST': 'PODCAST',
    'TCAT': 'PODCASTCATEGORY',
    'TDES': 'PODCASTDESC',
    'TGID': 'PODCASTID',
    'TKWD': 'PODCASTKEYWORDS',
    'WFED': 'PODCASTURL',
    'TPUB': 'PUBLISHER',
    'POPM:no@email': 'RATING MM',
    'POPM:Windows Media Player 9 Series': 'RATING WMP',
    'TDRL': 'RELEASETIME',
    'TSST': 'SETSUBTITLE',
    'TIT3': 'SUBTITLE',
    'TDTG': 'TAGGINGTIME',
    'SYLT': 'SYNCEDLYRICS',
    'TIT2': 'TITLE',
    'TSOT': 'TITLESORT',
    'TRCK': 'TRACKNUMBER',
    'USLT': 'UNSYNCEDLYRICS',
    'UFID': 'UNIQUEFILEID',
    'WXXX': 'WWW',
    'WOAR': 'WWWARTIST',
    'WOAF': 'WWWAUDIOFILE',
    'WOAS': 'WWWAUDIOSOURCE',
    'WCOM': 'WWWCOMMERCIALINFO',
    'WCOP': 'WWWCOPYRIGHT',
    'WPAY': 'WWWPAYMENT',
    'WPUB': 'WWWPUBLISHER',
    'WORS': 'WWWRADIOPAGE',
    'TDRC': 'YEAR'
}

APEV2_TO_VORBIS = {
    "Album Artist": "ALBUMARTIST",
    "TRACK": "TRACKNUMBER",
    "Cover Art (Other)": PT.OTHER,
    "Cover Art (Icon)": PT.FILE_ICON,
    "Cover Art (Other Icon)": PT.OTHER_FILE_ICON,
    "Cover Art (Front)": PT.COVER_FRONT,
    "Cover Art (Back)": PT.COVER_BACK,
    "Cover Art (Leaflet)": PT.LEAFLET_PAGE,
    "Cover Art (Media)": PT.MEDIA,
    "Cover Art (Lead Artist)": PT.LEAD_ARTIST,
    "Cover Art (Artist)": PT.ARTIST,
    "Cover Art (Conductor)": PT.CONDUCTOR,
    "Cover Art (Band)": PT.BAND,
    "Cover Art (Composer)": PT.COMPOSER,
    "Cover Art (Lyricist)": PT.LYRICIST,
    "Cover Art (Recording Location)": PT.RECORDING_LOCATION,
    "Cover Art (During Recording)": PT.DURING_RECORDING,
    "Cover Art (During Performance)": PT.DURING_PERFORMANCE,
    "Cover Art (Video Capture)": PT.SCREEN_CAPTURE,
    "Cover Art (Fish)": PT.FISH,
    "Cover Art (Illustration)": PT.ILLUSTRATION,
    "Cover Art (Band Logotype)": PT.BAND_LOGOTYPE,
    "Cover Art (Publisher Logotype)": PT.PUBLISHER_LOGOTYPE,
}

# TODO: mutagen里的akID没找到是什么意思
MP4_TO_VORBIS = {
    '©alb': 'ALBUM',
    'aART': 'ALBUMARTIST',
    'soaa': 'ALBUMARTISTSORT',
    'soal': 'ALBUMSORT',
    '©ART': 'ARTIST',
    'soar': 'ARTISTSORT',
    'tmpo': 'BPM',
    '©cmt': 'COMMENT',
    'cpil': 'COMPILATION',
    '©wrt': 'COMPOSER',
    'soco': 'COMPOSERSORT',
    'cprt': 'COPYRIGHT',
    '©prt': 'COPYRIGHT',
    'desc': 'DESCRIPTION',
    '©dir': 'DIRECTOR',
    'disk': ['DISCNUMBER', 'TOTALDISCS'],
    '©too': 'ENCODEDBY',
    '©gen': 'GENRE',
    '©grp': 'GROUPING',
    'apID': 'ITUNESACCOUNT',
    'rtng': 'ITUNESADVISORY',
    'plID': 'ITUNESALBUMID',
    'atID': 'ITUNESARTISTID',
    'cnID': 'ITUNESCATALOGID',
    'cmID': 'ITUNESCOMPOSERID',
    'sfID': 'ITUNESCOUNTRYID',
    'pgap': 'ITUNESGAPLESS',
    'geID': 'ITUNESGENREID',
    'hdvd': 'ITUNESHDVIDEO',
    'stik': 'ITUNESMEDIATYPE',
    'ownr': 'ITUNESOWNER',
    'purd': 'ITUNESPURCHASEDATE',
    '©mvi': 'MOVEMENT',
    '©mvn': 'MOVEMENTNAME',
    '©mvc': 'MOVEMENTTOTAL',
    '©nrt': 'NARRATOR',
    'pcst': 'PODCAST',
    'catg': 'PODCASTCATEGORY',
    'ldes': 'PODCASTDESC',
    'egid': 'PODCASTID',
    'keyw': 'PODCASTKEYWORDS',
    'purl': 'PODCASTURL',
    '©pub': 'PUBLISHER',
    'rate': 'RATE',
    'shwm': 'SHOWMOVEMENT',
    'sdes': 'STOREDESCRIPTION',
    '©nam': 'TITLE',
    'sonm': 'TITLESORT',
    'trkn': ['TRACKNUMBER', 'TOTALTRACKS'],
    'tves': 'TVEPISODE',
    'tven': 'TVEPISODEID',
    'tvnn': 'TVNETWORK',
    'tvsn': 'TVSEASON',
    'tvsh': 'TVSHOW',
    'sosn': 'TVSHOWSORT',
    '©lyr': 'UNSYNCEDLYRICS',
    '©wrk': 'WORK',
    '©day': 'YEAR'
}